// <auto-generated />
using System;
using InsuranceExtraction.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceExtraction.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326030938_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.Broker", b =>
                {
                    b.Property<int>("BrokerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("BrokerId");

                    b.ToTable("Brokers");
                });

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.CoverageLine", b =>
                {
                    b.Property<int>("CoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CurrentPremium")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LineOfBusiness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedLimit")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TargetPremium")
                        .HasColumnType("TEXT");

                    b.HasKey("CoverageId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("CoverageLines");
                });

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.Exposure", b =>
                {
                    b.Property<int>("ExposureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExposureType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExposureId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Exposures");
                });

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.Insured", b =>
                {
                    b.Property<int>("InsuredId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AnnualRevenue")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DotNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasColumnType("TEXT");

                    b.Property<string>("McNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearsInBusiness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("InsuredId");

                    b.ToTable("Insureds");
                });

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.LossHistory", b =>
                {
                    b.Property<int>("LossId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Claimant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LossAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LossDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LossType")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyYear")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReserveAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LossId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("LossHistory");
                });

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentList")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BrokerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailSubject")
                        .HasColumnType("TEXT");

                    b.Property<double>("ExtractionConfidence")
                        .HasColumnType("REAL");

                    b.Property<int?>("InsuredId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SubmissionId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("InsuredId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.CoverageLine", b =>
                {
                    b.HasOne("InsuranceExtraction.Domain.Entities.Submission", "Submission")
                        .WithMany("CoverageLines")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.Exposure", b =>
                {
                    b.HasOne("InsuranceExtraction.Domain.Entities.Submission", "Submission")
                        .WithMany("Exposures")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.LossHistory", b =>
                {
                    b.HasOne("InsuranceExtraction.Domain.Entities.Submission", "Submission")
                        .WithMany("Losses")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.Submission", b =>
                {
                    b.HasOne("InsuranceExtraction.Domain.Entities.Broker", "Broker")
                        .WithMany("Submissions")
                        .HasForeignKey("BrokerId");

                    b.HasOne("InsuranceExtraction.Domain.Entities.Insured", "Insured")
                        .WithMany("Submissions")
                        .HasForeignKey("InsuredId");

                    b.Navigation("Broker");

                    b.Navigation("Insured");
                });

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.Broker", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.Insured", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("InsuranceExtraction.Domain.Entities.Submission", b =>
                {
                    b.Navigation("CoverageLines");

                    b.Navigation("Exposures");

                    b.Navigation("Losses");
                });
#pragma warning restore 612, 618
        }
    }
}
